kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol-k8s
  labels:
    type: local
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /k8s
    server: 10.142.0.5
    readOnly: false 
