apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx3-exercicio
  namespace: default
spec:
  ports:
  - nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

